---
trainer:
  steps: 200
  workers: 2

  tensorboard_name:
  save_freq: 10

  PPOConfig:
    optimizer: adam
    OptimizerKwargs:
      lr: 0.00005
      betas: !!python/tuple [0.9, 0.999]
      eps: 1.0e-07
      weight_decay: 0
      amsgrad: false

    gamma: 0.99
    eta: 0.0
    gae_lambda: 0.95

    advantage_normalization: true

    eps: 0.2
    target_kl: 0.03
    entropy_coeff: 0.0
    entropy_decay_time: 100
    min_entropy: 0.0
    value_coeff: 1.0

    ppo_epochs: 10
    minibatch_size: 1024

    use_gpu:

model:

  activation: tanh
  initializer: orthogonal

  beta: false

  hidden_sizes: [64, 64, 64]
  separate_value: true

  sigma0: 0.4

  vec_hidden_layers: [32, 32]
  rel_hidden_layers: [32, 32]
  com_hidden_layers: [32, 32]


environment:
  agents: 12
  mode: default

  # Reward function
  potential: 1
  goal: 10
  collision: -0.05
  step_reward: -0.005

  standstill_weight: 0
  standstill_exponent: 0
  goal_speed_threshold: 0

  comfort_speed: 1.33
  comfort_speed_weight: -0.75
  comfort_speed_exponent: 1

  comfort_distance: 0
  comfort_distance_weight: 0

  # Energy
  e_s: 2.23
  e_w: 1.26

  # Observations
  sight_radius: 10
  sight_agents: 10
  sight_angle: 180


  ray_length: 10
  ray_degrees: 90
  ray_agent_vision: true
  destroy_raycasts: false

  # Spawn
  spawn_noise_scale: 0.5
  spawn_scale: 8

  grid_spawn: true
  group_spawn_scale: 1.5

  enable_obstacles: true
  shared_goal: true

  evaluation_mode: false
  save_path:
  early_finish: true
  dynamics: "PolarVelocity"
  observer: "Egocentric"
  initializer: "Corridor"
