---
trainer:
  steps: 1000
  workers: 16

  tensorboard_name:
  save_freq: 10

  PPOConfig:
    optimizer: adam
    OptimizerKwargs:
      lr: 0.00003
      betas: !!python/tuple [0.9, 0.999]
      eps: 1.0e-07
      weight_decay: 0
      amsgrad: false

    gamma: 0.99
    eta: 0.0
    gae_lambda: 0.9

    advantage_normalization: true

    eps: 0.25
    target_kl: 0.03
    entropy_coeff: 0.0
    entropy_decay_time: 100
    min_entropy: 0.0
    value_coeff: 1.0

    ppo_epochs: 20
    minibatch_size: 2048

    use_gpu:

model:
  input_size:
  num_actions:
  activation: relu
  discrete:

  hidden_sizes: [256, 256]
  separate_value: true

  rays_input_size:

  conv_filters:

  sigma0: 0.7

  vec_input_size: 4
  rel_input_size: 4
  vec_hidden_layers: [32, 32]
  rel_hidden_layers: [32, 32]
  com_hidden_layers: [32, 32]

  initializer: xavier_uniform