---
trainer:
  steps: 1000
  workers: 8

  tensorboard_name:
  save_freq: 10

  PPOConfig:
    optimizer: adam
    OptimizerKwargs:
      lr: 0.00003
      betas: !!python/tuple [0.9, 0.999]
      eps: 1.0e-07
      weight_decay: 0
      amsgrad: false

    gamma: 0.99
    use_ugae: false
    eta: 0.0
    gae_lambda: 0.9

    advantage_normalization: true

    eps: 0.2
    target_kl: 0.03
    entropy_coeff: 0.01
    entropy_decay_time: 100
    min_entropy: 0.0
    value_coeff: 1.0

    ppo_epochs: 20
    minibatch_size: 2048

    use_gpu:

model:
  beta: false
  activation: relu

  hidden_sizes: [256, 256]

  sigma0: 1.0
  std_head: false

  initializer: orthogonal