---
trainer:
  steps: 200
  workers: 8

  tensorboard_name:
  save_freq: 100

  PPOConfig:
    optimizer: adam
    OptimizerKwargs:
      lr: 0.00003
      betas: !!python/tuple [0.9, 0.999]
      eps: 1.0e-07
      weight_decay: 0
      amsgrad: false

    gamma: 1
    use_ugae: false
    eta: 0.0
    gae_lambda: 1

    advantage_normalization: true

    eps: 0.1
    target_kl: 0.03
    entropy_coeff: 0.0
    entropy_decay_time: 100
    min_entropy: 0.0
    value_coeff: 1.0

    ppo_epochs: 10
    minibatch_size: 200

    use_gpu:

model:
  beta: false
  activation: tanh

  hidden_sizes: [64, 64, 64, 64]

  sigma0: 0.5
  std_head: false

  initializer: orthogonal
