---
trainer:
  steps: 9
  workers: 8

  num_agents: 1

  tensorboard_name:
  save_freq: 10

  PPOConfig:
    optimizer: adam
    OptimizerKwargs:
      lr: 0.0003
      betas: !!python/tuple [0.9, 0.999]
      eps: 1.0e-07
      weight_decay: 0
      amsgrad: false

    gamma: 1.0
    eta: 0.0
    gae_lambda: 1.0

    advantage_normalization: true

    eps: 0.25
    target_kl: 0.03
    entropy_coeff: 0.0
    entropy_decay_time: 100
    min_entropy: 0.0
    value_coeff: 1.0

    ppo_epochs: 2
    minibatch_size: 80

    use_gpu: false

model:
  input_size:
  num_actions:
  activation: tanh
  discrete:

  hidden_sizes: [16, 16]
  separate_value: true

  rays_input_size:

  conv_filters:

  sigma0: 0.7

  vec_input_size: 4
  rel_input_size: 4
  vec_hidden_layers: [32, 32]
  rel_hidden_layers: [32, 32]
  com_hidden_layers: [32, 32]

  initializer: xavier_uniform
