---
trainer:
  steps: 200
  workers: 2

  tensorboard_name:
  save_freq: 100

  PPOConfig:
    optimizer: adam
    OptimizerKwargs:
      lr: 2e-4
      betas: !!python/tuple [0.9, 0.999]
      eps: 1.0e-07
      weight_decay: 0
      amsgrad: false

    gamma: 0.99
    eta: 0.0
    gae_lambda: 0.9056

    advantage_normalization: true

    eps: 0.08
    target_kl: 0.02
    entropy_coeff: 0.0
    entropy_decay_time: 500
    min_entropy: 0.0
    value_coeff: 1.0

    ppo_epochs: 20
    minibatch_size: 2048

    use_gpu:

model:
  input_size:
  rel_input_size:

  activation: tanh
  initializer: orthogonal

  beta: false

  hidden_sizes: [64, 64, 64]
  separate_value: true

  sigma0: 0.4

  vec_hidden_layers: [32, 32]
  rel_hidden_layers: [32, 32]
  com_hidden_layers: [32, 32]


environment:
  agents: 12
  mode: circle

  # Reward coefficients
  potential: 1.0
  goal: 10.0
  collision: -0.1
  step_reward: -0.005

  standstill_weight: -0.0
  stanstill_exponent: 1.0

  goal_speed_threshold: 10.1

  comfort_speed: 1.33
  comfort_speed_weight: -0.75
  comfort_speed_exponent: 1.0

  comfort_distance: 0.0
  comfort_distance_weight: 0.0

  e_s: 2.23
  e_w: 1.26

  sight_radius: 5.0
  sight_agents: 12.0

  spawn_noise_scale: 0.3
  spawn_scale: 8.0


  evaluation_mode: 0.0

  dynamics: "CartesianVelocity"  # CartesianVelocity, CartesianAcceleration, PolarVelocity, PolarAcceleration
  observer: "Relative"  # Relative, RotRelative, Absolute

