---
trainer:
  steps: 200
  workers: 2

  tensorboard_name: xu-true-original
  save_freq: 100

  PPOConfig:
    optimizer: adam
    OptimizerKwargs:
      lr: 0.0001
      betas: !!python/tuple [0.9, 0.999]
      eps: 1.0e-07
      weight_decay: 0
      amsgrad: false

    gamma: 0.99
    eta: 0.0
    gae_lambda: 0.928

    use_ugae: true

    advantage_normalization: true

    eps: 0.122
    target_kl: 0.0445
    entropy_coeff: 0.01387
    entropy_decay_time: 100
    min_entropy: 0.0
    value_coeff: 1.0

    ppo_epochs: 20
    minibatch_size: 2048

    use_gpu:

model:
  activation: leaky_relu
  initializer: orthogonal

  sigma0: 0.4

  beta: false

  hidden_sizes: [64, 64, 64]
  separate_value: true


  vec_hidden_layers: [128, 128, 128]
  rel_hidden_layers: [128, 128, 128]
  com_hidden_layers: [128, 128]
  emb_size: 64
  attention_heads: 2


environment:
  num_agents: 20
  initializer: "Circle"
  dynamics: "PolarAcceleration"
  observer: "Egocentric"
  rewarder: "DecisionRewarder"

  # Physics
  max_speed: 4.0
  max_acceleration: 5.0
  rotation_speed: 3.0

  # Spawn
  spawn_noise_scale: 1.5
  spawn_scale: 7

  grid_spawn: true
  group_spawn_scale: 1.5

  enable_obstacles: true
  block_scale: 3

  random_mass: true
  random_energy: false

  shared_goal: true

  # Unified reward

  r_bmr: 0.0
  r_drag: 0.0
  r_dynamics: 0.0
  r_potential: 0.0
  r_diff_potential: 0.0
  r_s_matching: 0.0
  r_s_matching_exp: 0.0
  r_speeding: 0.0
  r_exp_v_matching: -0.08
  r_exp_v_sigma: -0.85
  r_v_matching: 0.0
  r_goal: 1.0
  r_final: 0.0
  r_avg_final: 0.0

  collision: -0.1


  # Observations
  sight_radius: 10
  sight_agents: 50
  sight_angle: 180
  sight_acceleration: false

  rays_per_direction: 10
  ray_length: 10
  ray_degrees: 90
  ray_agent_vision: true
  destroy_raycasts: true




  evaluation_mode: false
  # save_path:  # This should probably be set manually
  early_finish: false
  nice_colors: true

  show_attention: false
  backwards_allowed: false

  # Legacy reward function
  potential: 1
  goal: 10
  step_reward: -0.005

  standstill_weight: 0
  standstill_exponent: 0
  goal_speed_threshold: 0

  comfort_speed: 1.33
  comfort_speed_weight: -0.75
  comfort_speed_exponent: 1

  comfort_distance: 0
  comfort_distance_weight: 0

  energy_weight: 1
  final_energy_weight: 1
  potential_energy_scale: 2
  complex_energy: true

model_type: "relation"
